# This is a basic workflow to help you get started with Actions

name: Build, Pack & Push NuGets

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-pack-and-push:
    # The type of runner that the job will run on
    runs-on: windows-latest

    env:
      Solution_Name: EnigmatiKreations.Framework.sln                         
      Test_Project_Path: Tests\EnigmatiKreations.Framework.UnitTests\EnigmatiKreations.Framework.UnitTests.csproj
      PACKAGES_ACCESS_TOKEN: ${{ secrets.PACKAGES_ACCESS_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Install `msbuild` command
      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v1.1

      # Install `dotnet` command
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build packages for Release
        run: msbuild $env:Solution_Name -t:rebuild -verbosity:diag -p:Configuration=Release
        
      - name: Pack NuGets
        run: msbuild $env:Solution_Name -t:pack -p:Configuration=Release
        
      - shell: pwsh
        name: Push NuGets

        run: |
             dotnet nuget push .\EnigmatiKreations.Framework.ApiManager\bin\Release\*.nupkg --source "github" --api-key "$env:PACKAGES_ACCESS_TOKEN"
             dotnet nuget push .\EnigmatiKreations.Framework.Controls\bin\Release\*.nupkg --source "github" --api-key "$env:PACKAGES_ACCESS_TOKEN"
             dotnet nuget push .\EnigmatiKreations.Framework.Managers\bin\Release\*.nupkg --source "github" --api-key "$env:PACKAGES_ACCESS_TOKEN"
             dotnet nuget push .\EnigmatiKreations.Framework.MVVM\bin\Release\*.nupkg --source "github" --api-key "$env:PACKAGES_ACCESS_TOKEN"
             dotnet nuget push .\EnigmatiKreations.Framework.Persistence\bin\Release\*.nupkg --source "github" --api-key "$env:PACKAGES_ACCESS_TOKEN"
             dotnet nuget push .\EnigmatiKreations.Framework.Utils\bin\Release\*.nupkg --source "github" --api-key "$env:PACKAGES_ACCESS_TOKEN"
        
        

